server:
  port: 8848
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_only_dev?serverTimezone=Asia/Taipei
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true