server:
  port: 10002
spring:
  application:
    name: TestWebApi
  boot:
    admin:
      client:
        url: http://127.0.0.1:10001
management:
  endpoints:
    web:
      exposure:
        include: '*'