server:
  port: 5555
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tds_dev
    username: root
    password: 1234
  main:
    banner-mode: off
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.dao: debug